version: '3.3'

services:
  ps1_db:
    image: mysql:5.7
    volumes:
     - /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ps
      MYSQL_USER: ps
      MYSQL_PASSWORD: ps
    command: mysqld --sql_mode=""
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - ps1_db:db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin

  ps1:
    depends_on:
      - ps1_db
    image: prestashop/prestashop:1.7.1.0
    ports:
      - "8080:80"
    restart: always
    environment:
      PS_ERASE_DB: 0
      DB_SERVER: ps1_db
      DB_USER: ps
      DB_PASSWD: ps
      DB_NAME: ps
      PS_DEV_MODE: 0
      PS_DOMAIN: localhost:8080
      PS_FOLDER_ADMIN: admin_ps
      PS_FOLDER_INSTALL: install_ps
      ADMIN_MAIL: test@prestashop.com
      ADMIN_PASSWD: 12345678
    volumes: 
    - ./data:/var/www/html
    - ./data/mysql:/var/lib/mysql
    - ./override:/var/www/html/override

